@startuml
class CreateShape {
    shape : string
    + CreateShape(canvas:Canvas, shape:string)
    + Execute() : void
    + Undo() : void
}
Command <|-- CreateShape
CreateShape --> "newcanvas" Canvas
@enduml
